// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDztKiuxD57xyy2JR0yn9mZVjIuokzPdNU',
    appId: '1:586552262655:web:79955cf59e9a41d17c71ca',
    messagingSenderId: '586552262655',
    projectId: 'matrix-idea-notes',
    authDomain: 'matrix-idea-notes.firebaseapp.com',
    storageBucket: 'matrix-idea-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJ_X2Gz6ssMgbUKpJW9nWZa9H5NeVMzM',
    appId: '1:586552262655:android:db200527a680387a7c71ca',
    messagingSenderId: '586552262655',
    projectId: 'matrix-idea-notes',
    storageBucket: 'matrix-idea-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4frUb9BhnDbYAnHKIeT6lV3tzDSkOnA0',
    appId: '1:586552262655:ios:4ca8c7844e11198d7c71ca',
    messagingSenderId: '586552262655',
    projectId: 'matrix-idea-notes',
    storageBucket: 'matrix-idea-notes.appspot.com',
    iosClientId: '586552262655-v0mrsoamm7a2lh28si8uonalvd7lpl7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4frUb9BhnDbYAnHKIeT6lV3tzDSkOnA0',
    appId: '1:586552262655:ios:4ca8c7844e11198d7c71ca',
    messagingSenderId: '586552262655',
    projectId: 'matrix-idea-notes',
    storageBucket: 'matrix-idea-notes.appspot.com',
    iosClientId: '586552262655-v0mrsoamm7a2lh28si8uonalvd7lpl7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
